### ISSUE TITLE
FAQ #4 (part 2)

### ISSUE THREAD

**Issue by ghost** [x-tools/SuperCount#10]
When used to profile multiple users on a wiki that requires opting in (https://tools.wmflabs.org/supercount/index.php?user=Lucas+Thoms|Cyberpower678&project=commons.wikimedia as an example), FAQ 4 recommends creating an opt in page at an invalid title (User:Lucas&nbsp;Thoms|Cyberpower678/EditCounterOptIn.js).

![selection_038](https://cloud.githubusercontent.com/assets/8193078/3616789/25a0e53e-0dd7-11e4-9001-97a0fb7b8349.png)

**Comment by cyberpower678** [comment]
Grrr.  I just closed my PHP debugger.

**Comment by cyberpower678** [comment]
Fixed.
