### ISSUE TITLE
Pie chart in overview

### ISSUE THREAD

**Issue by FAE-Sonata** [x-tools/SuperCount#12]
The pie chart should specify the counts do NOT included deleted edits

**Comment by cyberpower678** [comment]
They will soon.

**Comment by JohnnyAu** [comment]
The pie chart no longer shows up for me.

**Comment by ghost** [comment]
Confirmed from here too.

**Comment by cyberpower678** [comment]
Please see https://en.wikipedia.org/w/index.php?title=User_talk:Cyberpower678&oldid=618463456#Edit_counter_problem for details regarding the missing pie chart issue.
