### ISSUE TITLE
Error in the API

### ISSUE THREAD

**Issue by KernelFreeze** [x-tools/SuperCount#16]
Hi, I try to get my contributions in 'https://tools.wmflabs.org/supercount/api.php?user=Miguel2706&project=es.wikipedia.org', but it does not work, and says "Fatal error: Cannot pass parameter 4 by reference in /data/project/supercount/public_html/api.php on line 65" :(
PS: It's for a bot

**Comment by cyberpower678** [comment]
Crap.  I must have broken a bot or 2 when applying that update.  I'll have it fixed tomorrow.

**Comment by cyberpower678** [comment]
There you go.  That should do it.
