### ISSUE TITLE
'Useful info' about orain

### ISSUE THREAD

**Issue by revi** [x-tools/SuperCount#20]
> The edit counter now runs for Orain <br />Try it out. Sign up on Orain, if you're interested in creating your own free ad-free community driven wiki.

I want this to be changed to

> The edit countee now runs for Orain, ad-free community driven wiki. <br /> If you are interested in creating your own wiki, sign up on orain.
> **sign up** will have a link to new account special page on orain meta.

**Comment by cyberpower678** [comment]
countee?

**Comment by waldyrious** [comment]
sounds like a typo (qwERty)

**Comment by cyberpower678** [comment]
@revi should I just make it an ad on the edit counter?

**Comment by revi** [comment]
Closing as stale.
