### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by ghost** [x-tools/SuperCount#21]
OAuth log in link doesn't work if you enter the project without the .org.

In other words, on https://tools.wmflabs.org/supercount/index.php?user=Lucas+Thoms&project=en.wikipedia the link doesn't work; on https://tools.wmflabs.org/supercount/index.php?user=Lucas+Thoms&project=en.wikipedia.org it does.

The error message is **An OAuth error occured. Details: Failed to successfully login. Reported error: Curl error: Couldn't resolve host 'en.wikipedia'**. It sounds to me like OAuth is assuming the user used the full project address; all links to the counter on Wikipedia still use the legacy **en.wikipedia**, which makes things a little weird

**Comment by cyberpower678** [comment]
Something similar happens to wikidata.org without the www.  However, for project parameters lacking .org, just click the link again.  It should work.  To get it to work for wikidata, use project=www.wikidata.org.

**Comment by cyberpower678** [comment]
Fixed both bugs.
