### ISSUE TITLE
Wikipedia use on a page?

### ISSUE THREAD

**Issue by pcoughlin** [x-tools/SuperCount#23]
I have tried putting this code into my user page:

```
Editcount={{editcount}}
```

and received this output:
Editcount=Edit count for {{{1}}} 

Tried adding a parameter, like this:

```
{{editcount|user_name=xyzzy529}} 
```

but had the same result.

I would like to use the editcount to subst: into the page and have a current update of the number each time I look at the page.

My goal is to do something like this:

```
{{Service award progress|year=2007|month=8|day=24|edits={{subst:editcount|user_name=xyzzy529}} }} 
```

**Comment by cyberpower678** [comment]
I don't think that's what it's for.

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by ghost** [comment]
Paul, that template isn't designed for that. All that
{{editcount|Cyberpower678}} does is link to
https://tools.wmflabs.org/supercount/index.php?user=Cyberpower678&project=en.wikipedia.org.
It's not supposed to show an actual number. AFAIK there's no way to do that
automatically (except, I guess, for a bot).

**Comment by cyberpower678** [comment]
Actually Lucas, with the use of a Lua Module, it can be done.  The supercount API is built for automated tasks.

**Comment by ghost** [comment]
Has anyone done that?

**Comment by cyberpower678** [comment]
Not to my knowledge.

**Comment by waldyrious** [comment]
FYI, the [LiveEditCounter](http://en.wikipedia.org/wiki/User:UBX/LiveEditCounter) userbox uses a javascript function to access the API via XHR (Ajax) and get the edit count.

Also, User:PleaseStand's [User info](http://en.wikipedia.org/wiki/User:PleaseStand/User_info) script uses a similar technique for the same effect.

**Comment by cyberpower678** [comment]
I'm not sure exactly what the issue is?  If your asking to use this edit counter's api, then yes.

Gesendet von Maximilian's iPhone. 
(Sent from Maximilian's iPhone.)

**Comment by pcoughlin** [comment]
Thanks waldyrious pointed me in a good direction.  I used some of that code to get what I wanted.
