### ISSUE TITLE
API

### ISSUE THREAD

**Issue by dimastbk** [x-tools/SuperCount#28]
API down again.

http://tools.wmflabs.org/supercount/api.php?user=dima_st_bk&project=ru.wikipedia.org

Catchable fatal error: Argument 2 passed to API::__construct() must be an instance of Wiki, array given, called in /data/project/supercount/public_html/api.php on line 69 and defined in /data/project/supercount/public_html/core.php on line 141 Call Stack: 0.0031 987064 1. {main}() /data/project/supercount/public_html/api.php:0 0.4899 2258856 2. API->__construct() /data/project/supercount/public_html/api.php:69

**Comment by cyberpower678** [comment]
Urgh.  A stability update I applied to the core and index.php files that I forgot to apply to api.php. :/

**Comment by dimastbk** [comment]
Can you update api.php? It took 3 days.

**Comment by cyberpower678** [comment]
Give me a few hours.  My Thanksgiving break will be starting soon.
