### ISSUE TITLE
Broken on Meta

### ISSUE THREAD

**Issue by Ltrlg** [x-tools/SuperCount#34]
I cannot use supercount on Meta: no graphs are shown and there are some `Notice: Undefined offset` in _Monthly Stats_/_Namespaces_. See [my statistics](https://tools.wmflabs.org/supercount/index.php?user=Ltrlg&project=meta.wikimedia) for an example.

**Comment by Ltrlg** [comment]
On meta, caused by the _Graph_ extension (ns 484-487).

**Comment by cyberpower678** [comment]
Fixed.
