### ISSUE TITLE
Pie chart dissapeard. Can you do somethink with it?

### ISSUE THREAD

**Issue by urbanecm** [x-tools/SuperCount#36]
Here is a picture. 

![Where is the pie chart?](https://cloud.githubusercontent.com/assets/10050467/9282313/d05b73e8-42cb-11e5-8224-d77b475074af.png)

I am using Windows 8.1 and Chrome 44.0.2403.130 m. 

Thank you for fixing, 
Martin Urbanec
Urbanecm

**Comment by Ltrlg** [comment]
Same issue as #34, but now the problem is present for almost all wikis, because of the new  namespaces created by the _Gadgets_ extension (2300 to 2303).

**Comment by cyberpower678** [comment]
Fixed.
