### ISSUE TITLE
Why is there a difference between SuperCount and Special:Preferences

### ISSUE THREAD

**Issue by dvorapa** [x-tools/SuperCount#46]
The numbers of total edits doesn't match. Both with or without deleted edits. Why?

**Comment by cyberpower678** [comment]
Match to what?

**Comment by dvorapa** [comment]
@cyberpower678 to the number in Special:Preferences (see header)

**Comment by cyberpower678** [comment]
The edit counter counts page moves and other stuff that shows up in the edit history of a page.  The number in preferences, is just a tally saved in the DB.

**Comment by dvorapa** [comment]
@cyberpower678 I know, but where is the difference between the calculation of SuperCount and the notation into db? Do you know? Why some users have got higher number in SuperCount and some higher number in Special:Preferences?

**Comment by cyberpower678** [comment]
Some edits get deleted.  The super count counts live edits.  Preferences doesn’t take that into account.  Preferences is more or less, less accurate.

**Comment by dvorapa** [comment]
@cyberpower678 Okay, thank you
